### ISSUE TITLE
Need help on understanding this assignment 

### ISSUE THREAD

**Issue by EmmaJLussier** [EmmaJLussier/distributed-cards#1]
@hellachella @raven-rhea 

Hey! so I'm having a hard time understanding this assignment ,How do you combine css grid and flexbox? I'm not sure what content I'm suppose to apply each to.

**Comment by raven-rhea** [comment]
Hey Emma, So start by examining the screenshot, There is a list of cards that are in a grid. The cards themselves have a bunch of info and button at the bottom, To get those cards to all have the same length with the button at the bottom a good way to go about that is display: flex; 
![sketch](https://user-images.githubusercontent.com/55094082/113479015-6527b280-945a-11eb-88e7-302c38b79c66.jpg)

**Comment by raven-rhea** [comment]
So your ol is where you want to use grids and the li's will use display flex

**Comment by EmmaJLussier** [comment]
Thank you Raven :)

**Comment by raven-rhea** [comment]
No problem :)

**Comment by EmmaJLussier** [comment]
I need some help on how to format the cards in a row like in the screenshot.
<img width="483" alt="Screen Shot 2021-04-03 at 9 36 23 AM" src="https://user-images.githubusercontent.com/77282460/113480036-4c220000-9460-11eb-9dec-75070cc68b23.png">

**Comment by raven-rhea** [comment]
make sure you set your grid-template-columns: 1fr 1fr; so that each card will take up one fraction

**Comment by EmmaJLussier** [comment]
Ah ha! Thank you

**Comment by EmmaJLussier** [comment]
I think I'm almost there I'm just having problems with the links borders and the h2. 
<img width="966" alt="Screen Shot 2021-04-03 at 11 27 11 AM" src="https://user-images.githubusercontent.com/77282460/113483079-aa0a1400-946f-11eb-8cb5-83a983b300bb.png">

**Comment by raven-rhea** [comment]
I dont think you want align centered, so I think you should change your flex direction to row,  and add justify-content: space-between;

**Comment by EmmaJLussier** [comment]
<img width="966" alt="Screen Shot 2021-04-03 at 12 01 44 PM" src="https://user-images.githubusercontent.com/77282460/113484057-62d25200-9474-11eb-9d5b-f12277a888e3.png">
I think I need some help with the padding between the content in the li

**Comment by raven-rhea** [comment]
Hmmm your sooo close its just some padding or margin errors. There's too much margin-top on your h2's and maybe not enough on your p's. Whenever things aren't lining up like this start with the first thing that's off, which is your h2 should have less margin top

**Comment by EmmaJLussier** [comment]
I think I fixed my h2s now the paragraphs and links are giving me a hard time the line length seems to be off and margins
![Screen Shot 2021-04-03 at 7 50 05 PM](https://user-images.githubusercontent.com/77282460/113494396-d2b4fc80-94b5-11eb-9698-045c81c92d90.png)
reference

![Screen Shot 2021-04-03 at 7 50 18 PM](https://user-images.githubusercontent.com/77282460/113494402-dea0be80-94b5-11eb-9d1e-b2fa8fdf9464.png)
mine

**Comment by EmmaJLussier** [comment]
What values do you use for the padding and margins

**Comment by raven-rhea** [comment]
Margin bottom on your h1 should be 1.5rem. Try also the p put margin: 0 0 auto;

**Comment by EmmaJLussier** [comment]
Tried it out 19% away

**Comment by EmmaJLussier** [comment]
<img width="969" alt="Screen Shot 2021-04-04 at 7 00 10 PM" src="https://user-images.githubusercontent.com/77282460/113523784-02c4d400-9578-11eb-959c-d107ce66ec65.png">
This is where i am now

**Comment by raven-rhea** [comment]
K so if you change your h1 to this and add main 
h1 {
  margin: 0 0 1.5rem;
}

main {
  padding: 1rem;
}

take the margin off you ol and add a padding-top: 1.5rem on the p

**Comment by EmmaJLussier** [comment]
Thank you So much Raven you’re amazing! :)

**Comment by raven-rhea** [comment]
No problem!
